### PR TITLE
Fix deselection of multiple ensembles

### LINKED ISSUE #251: Clear selection should remove charts

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Issue**
Resolves #251 

**Approach**
Generalize behaviour for removing one ensemble to removing multiple ensembles.

## Pre review checklist

- [X] Added appropriate labels

### CODE REVIEW

**Comment by oysteoh** [comment]
Jenkins: Test this please!

**Comment by oysteoh** [comment]
Jenkins: Test this please!

**Review by oysteoh — APPROVED** [review]
LGTM :+1:

**Comment by valentin-krasontovitsch** [comment]
thanks a bunch! gonna try it out in a bit

**Pull request merged**
