### PR TITLE
Add mypy support

### LINKED ISSUE #136: Apply MyPy for this repository

### PR DESCRIPTION
**Pull request by xjules**
Resolves #136 
modules to be done:
- [x] views
- [x] controllers
- [x] plugins
- [x] models
- [x] data_loaders
- [x] others

TODOs:
- [x] remove circular dependencies
- [x] remove as many `Any` as possible
- [x] fix `Union[None, x] -> Optional[x]`
- [x] double check helper functions
- [x] make sure tests are green

### CODE REVIEW

**Comment by oysteoh** [comment]
I think it would be beneficial having one commit introducing mypy. Agree?

**Comment by oysteoh** [comment]
When in response correlation view, initially when selecting responses / parameters nothing is happening.
Skjermbilde 2021-03-24 kl  13 20 32

**Comment by oysteoh** [comment]
Then , after successfully selected some responses / parameters, the chart on the right side moves out of my screen. The labels for the selected items are shown as object-references as well instead of proper names.
Skjermbilde 2021-03-24 kl  13 23 36

**Comment by oysteoh** [comment]
just by selecting an ensemble - you now get a lot of data visualized "by default". I have not selected anything here, still all of the parameters are showing up. ( This also goes for the rest of the views - there seems to be "preselected" stuff immidiately after selecting an ensemble

**Comment by oysteoh** [comment]
Cannot remember seen this before - the lines of the realizations having dots on the datapoints . Makes it really "fluffy". Has it been like this before / as big as this before ? - just me not remembering it? 
Skjermbilde 2021-03-24 kl  13 34 28

**Comment by xjules** [comment]
> I think it would be beneficial having one commit introducing mypy. Agree?

There's a stand alone commit that introduces `mypy.ini` and the test for it on github actions. Or you meant something else?

**Comment by oysteoh** [comment]
> > I think it would be beneficial having one commit introducing mypy. Agree?
> 
> There's a stand alone commit that introduces `mypy.ini` and the test for it on github actions. Or you meant something else?

i was thinking more in lines of squashing all of your commits. But i'm not totally sure it is necessary. I think you commits now seems clean and nice. But - do we need all of those in the masterbranch - or would it be better having one commit - `apply mypy throughout the repository` ?

**Comment by xjules** [comment]
> When in response correlation view, initially when selecting responses / parameters nothing is happening.
Should be fixed now!

**Comment by xjules** [comment]
> just by selecting an ensemble - you now get a lot of data visualized "by default". I have not selected anything here, still all of the parameters are showing up. ( This also goes for the rest of the views - there seems to be "preselected" stuff immidiately after selecting an ensemble

This;s solved at least for parameter plot.Haven't seen it in other views.

**Comment by xjules** [comment]
> Cannot remember seen this before - the lines of the realizations having dots on the datapoints . Makes it really "fluffy". Has it been like this before / as big as this before ? - just me not remembering it?

I've changed it wrt. whether it is an index based or temporal response.

**Comment by xjules** [comment]
> Then , after successfully selected some responses / parameters, the chart on the right side moves out of my screen. The labels for the selected items are shown as object-references as well instead of proper names.

Should be fixed too now!

**Review by oysteoh — APPROVED** [review]
🚀

**Pull request merged**
