### PR TITLE
Change info text display

### LINKED ISSUE #357: Response Correlation Viewer: Improve info text display
**Is your feature request related to a problem? Please describe.**
The info text at the bottom of the response correlation viewer plugin shows

- a list of all responses
- the active response in bold
- the active parameter, in bold
- the current x index / value

this list is simple formatted text, and at the bottom of the page. I believe that this information deserves a more prominent role - personally, i hardly noticed it when I started looking at this plugin, and it is vital information, as there's a lot of changes going on when one clicks for instance on the heatmap. changes which appear very mysterious to somebody who doesn't quite know what's going on with this plugin.

**Describe the solution you'd like**
I think doing some changes might improve the user experience, and increase clarity and usability of this plugin:

- placing the information in a more prominent position;
- styling the information in a more prominent way;
- perhaps indicating changes in the information using some animation or transition (no idea if this is possible, or how difficult it is at the moment)

**Describe alternatives you've considered**
Leaving it as is seems unsatisfactory, but perhaps I'm just a noob, and to users, who know what these plots are and what they're doing with them, this might be completely clear and the "improvement" wou;ldn't actually help much

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Issue**
Resolves #357

**Approach**
We pull out the info text into its own callback.

We remove the list of all selected responses, as this is visible in the response selector.

We move the text above the plots, and center it, and make it into badges.

We also move all the options to the bottom, and rearrange slightly visually.

**Screenshots**

info-text

## Pre review checklist

- [X] Added appropriate labels

### CODE REVIEW

**Comment by oysteoh** [comment]
I think this is a very nice and good improvement to how things looks like ! :+1:  You need a rebase and squash of your commits, then i will approve !

**Comment by valentin-krasontovitsch** [comment]
thank you! still trying to get jenkins to be happy, but will rebase and zucchini as well!

**Comment by valentin-krasontovitsch** [comment]
rebased and squashed, jenkins to be ignored until we have a successful bleeding build, waiting for final :bacon:

**Comment by valentin-krasontovitsch** [comment]
sorry had to push another commit, which shuffled the tour steps around according to the relocation of elements on the page.

for now single commit, so it can be reviewed in isolation - gonna squash it later.

**Review by oysteoh — APPROVED** [review]

**Pull request merged**
