### PR TITLE
Fix removal of plots upon deselection of parameters / responses

### LINKED ISSUE #251: Clear selection should remove charts

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Issue**
Resolves #251

**Approach**
generalize deletion of plots from deselecting a single item to deselecting several items

## Pre review checklist

- [X] Added appropriate labels

**again unsure if i should the milestone or any other labels besides bug**

### CODE REVIEW

**Comment by valentin-krasontovitsch** [comment]
also - should I add a test for this? not sure how easy that would be, but I could try to look into it. a quick glance showed that there aren't many tests to go on, perhaps because it is difficult to test the controller by itself?

**Comment by ertomatic** [comment]
Can one of the admins verify this patch?

**Comment by DanSava** [comment]
Jenkins safe to test

**Comment by DanSava** [comment]
Jenkins add to whitelist

**Comment by valentin-krasontovitsch** [comment]
thanks, I'll have another tour of the tests and see that I compose a test that covers this!

**Review by DanSava — APPROVED** [review]
Looks good :+1:

**Comment by valentin-krasontovitsch** [comment]
I've added a test - just to satisfy the review process, would you mind having another look (at the test code), @DanSava ? thank you! I always feel like my front end testing is brittle, so I would appreciate another set of eyes on it. relying on hard coded IDs or css classes, and waiting a certain time (NB: hack!) is just part of what makes me feel a bit uneasy about the test... but i didn't see a better way at the moment.

**Review by DanSava — APPROVED** [review]
Test looks good :+1: you can merge when you are ready.

**Comment by valentin-krasontovitsch** [comment]
perfect, thanks a lot! ^^

**Pull request merged**
