### PR TITLE
Handle labels in the parameter list from updated API.

### LINKED ISSUE #211: Displaying large ensembles in the ensemble view is slow
**Additional context**

Large ensemble:
* 200 realizations 
* 10-20 responses sized 20.000 values per response

Ensemble view is slow:
Takes 30-50 seconds to display 4-5 large ensembles in the ensemble view on startup and also when changing the viewed page. 

**Update**

Slow drawing time is related to webviz ert getting parameter labels for each of the parameters in an ensemble. If the ensemble has 200 + parameters this results in 200 + HTTP calls for the parameter labels.

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #211

**Approach**
Match updates in dark storage and ert storage that returns labels as part of parameters when querying the `parameters` endpoint

### CODE REVIEW

**Review by oysteoh — APPROVED** [review]
:rocket:

**Review by oysteoh — APPROVED** [review]
:rocket:

**Comment by DanSava** [comment]
Jenkins test this please

**Comment by oysteoh** [comment]
Jenkins: Test this please!

**Pull request merged**
