### PR TITLE
Update legends

### PR DESCRIPTION
**Pull request by autt**
Solves #113 

Testing out checkbox for legend description and short repr name for ensembles.

### CODE REVIEW

**Comment by ManInFez** [comment]
I am wondering if we should have this a single checkbox which works for all plots?

**Comment by autt** [comment]
@ManInFez That might be a good idea. I will test it :+1:

**Review by oysteoh — CHANGES_REQUESTED** [review]
This looks as it works like intended - good work! 🚀  

Is it necessary having all the commits, or could those be squashed into one or a couple of commits?

**Comment by autt** [comment]
> This looks as it works like intended - good work! rocket
> 
> Is it necessary having all the commits, or could those be squashed into one or a couple of commits?

Squashed some commits, can squash more if wanted :smile:

**Review by oysteoh — APPROVED** [review]

**Pull request merged**
