### PR TITLE
Add response correlation gif to readme

### LINKED ISSUE #385: Add response correlation GIF use tutorial to readme
Depending on if we end up merging https://github.com/equinor/webviz-ert/pull/384

Add the following gif to the readme file or the one representing the actual user-facing response correlation page.

* **Response Correlation**
response_correlation

### PR DESCRIPTION
**Pull request by DanSava**
**Issue**
Resolves #385

### CODE REVIEW

**Comment by DanSava** [comment]
Jenkins test this

**Comment by DanSava** [comment]
Jenkins test this

**Review by oysteoh — APPROVED** [review]
You need my pr in order to get jenkins to test correctly - other than that it is good to go! 🚀

**Comment by DanSava** [comment]
Jenkins test this

**Comment by DanSava** [comment]
Jenkins test this

**Pull request merged**
