### PR TITLE
Fix superimposing layout 378

### LINKED ISSUE #378: Is there a way to guarantee that plots do not superpose information?
**Describe the bug**
In both "Plot viewer" and "Parameter comparison viewer", I observed that some text is superposed by plot in the section immediately above (see example in the image). Is there a way we can guarantee that this does not happen, independently of the screen size

**To Reproduce**
1. Having large names for the parameters and trying to plot them in the views described above.

**Expected behavior**
To see the complete name of the parameter independently of its size.

**Screenshots**
Screenshot from 2022-08-18 15-23-39

### PR DESCRIPTION
**Pull request by valentin-krasontovitsch**
**Issue**
Closes #378

**Approach**
Increase height of columns in response view; Let labels overflow and show overflow in parameter comparison view.

## Pre review checklist

- [X] Added appropriate labels

### CODE REVIEW

**Comment by valentin-krasontovitsch** [comment]
coolio! i guess i should have mentioned that, sorry, there are some images in the issue, and also one or two questions - i really should not rely on the github notifications...

please see if the images there suffice.

also, gonna check out the jenkins!

**Comment by valentin-krasontovitsch** [comment]
jenkins, retest this please.

**Comment by hnformentin** [comment]
The failure in Jenkins was due to bleeding not having built successfully:
https://equinor.slack.com/archives/C01MCMWD075/p1661345170111939

**Comment by valentin-krasontovitsch** [comment]
results of this change, visualized:

i found a way of hacking the labels visible after all: move them down, and set overflow to visible. but: on mouseover, one sees that the border of the container "cuts off" the labels, see screenshots.

mouse not on container, borders not visible, OK:

hack-ok

mouse on container, borders visible, it's subtle but off:

hack-borders

**Review by DanSava — APPROVED** [review]
LGTM

**Comment by valentin-krasontovitsch** [comment]
jenkins build aborted by user. orginally passed, before my comment edit triggered a rerun. merging now.

**Comment by hnformentin** [comment]
Nice @valentin-krasontovitsch.
I tested on the context that led the bug to be reported and it worked.
Screenshot from 2022-08-30 13-57-24

**Review by hnformentin — APPROVED** [review]

**Pull request merged**
